### ISSUE TITLE
Corresponding Author ORCIDs

### ISSUE THREAD

**Issue by ahwagner** [ahwagner/vicckb#40]
From most recent instructions:

>Before resubmitting the final version of the manuscript, if you are listed as a corresponding author on the manuscript, please follow the steps below to link your account on our MTS with your ORCID. If you don’t have an ORCID yet, you will be able to create one in minutes. If you are not listed as a corresponding author, please ensure that the corresponding author(s) comply.

>1. From the home page of the MTS) click on ‘Modify my Springer Nature account’ under ‘General tasks’.
>2. In the ‘Personal profile’ tab, click on ‘ORCID Create/link an Open Researcher Contributor ID(ORCID)’. This will re-direct you to the ORCID website.
>3.
>    1. If you already have an ORCID account, enter your ORCID email and password and click on ‘Authorize’ to link your ORCID with your account on the MTS.
>    2. If you don’t yet have an ORCID, you can easily create one by providing the required information and then click on ‘Authorize’. This will link your newly created ORCID with your account on the MTS.

>IMPORTANT: All authors identified as ‘corresponding authors’ on the manuscript must follow these instructions. Non-corresponding authors do not have to link their ORCIDs, but please note that it will not be possible to add/modify ORCIDs at proof. Thus, if they wish to have their ORCID added to the paper, they must also follow the above procedure prior to acceptance. 

@obigriffith and @malachig, I need each of you to verify this is completed for your respective accounts.

**Comment by obigriffith** [comment]
Mine is already linked.

**Comment by malachig** [comment]
Same here.
